# Discretizations
T: 10000
D: 10000

# Sim settings
saem: 1
seed: 2

# Load Path
data_path: 'data/simData_1e6-0-1-0_0.2-0.4-0.7-0.07-450.pkl'
log_path: 'logs'
name: 'seedX-rand-mu5'

# Optimization Settings
eta1: 5e-4
eta2: 5e-3
eta3: 5e-4
eta4: 5e-4

decay-gd: 200
decay-em: 1
iters: 500
