# Discretizations
T: 10000
D: 10000

# Sim settings
saem: 1   
seed: 0

# Load Path
data_path: 'data/simData_1e6-0-1-0_0.2-0.4-0.7-0.07-450.pkl'
log_path: 'logs'
name: 'uniform-len-2'

# Optimization Settings
eta1: 5e-3
eta2: 5e-3
eta3: 5e-3
eta4: 1e-3

decay-gd: 25
decay-em: 1
iters: 400
